### PR TITLE
Add support for nix-darwin

### LINKED ISSUE #60: darwin build failure: `system.activationScripts.users.deps` does not exist
I'm using Nix (with nix-darwin and flakes support) on macOS 11.6 (though this happened on previous versions of macOS too). I've configured agenix as suggested in the README, but `nix build` fails with the following error:

```
error: The option `system.activationScripts.users.deps' does not exist. Definition values:
       - In `<unknown-file>':
           [
             "agenixRoot"
           ]
```

I think [this](https://github.com/LnL7/nix-darwin/blob/master/modules/users/default.nix) is the relevant file in nix-darwin that configures `system.activationScripts.users`, and `deps` is not one of its attributes.

Bear with me, as I'm new-ish to Nix and haven't yet started working with NixOS: judging by the declaration of `deps` as a required(?) attribute for activation scripts in NixOS [here](https://github.com/NixOS/nixpkgs/blob/9c566248dff1430c3d6e91e300b7d0b8320e012a/nixos/modules/system/activation/activation-script.nix#L76-L86), I'm guessing it would make more sense for nix-darwin to add support for this rather than have agenix accommodate nix-darwin? If so, I'm not sure about the level of effort there, so I'd welcome any advice about a temporary workaround for the time being.

### PR DESCRIPTION
**Pull request by montchr**
This is an updated take on @cmhamill's work in #79 accommodating a lot of recent changes to the module in `main`. Props to @cmhamill for getting this most of the way there.

I'm tracking this branch in my own system flake and it's working well on macOS. I haven't tested on NixOS.

Fixes #60

### CODE REVIEW

**Comment by mitchty** [comment]
Just as a note from a random nix-darwin user, this all seems to work fine in testing with my own flake seetup and thanks for getting it to work!

What I would add to the pr is these outputs to stay close to what home-manager does:
```
Unstaged changes (1)
modified   flake.nix
@@ -10,6 +10,9 @@
     agenix = system: nixpkgs.legacyPackages.${system}.callPackage ./pkgs/agenix.nix {};
   in {
 
+    darwinModules.age = import ./modules/age.nix;
+    darwinModule = self.darwinModules.age;
+
     nixosModules.age = import ./modules/age.nix;
     nixosModule = self.nixosModules.age;
 
```

If anyone else wants to poke around or play along at home, my nix flake config commit using this pr for restic backups is here:
https://github.com/mitchty/nix/commit/ccaf2fa7c3c53a2f9ce693e551ed511442cd74fb

Thanks again for getting this to work on macos!

**Comment by rtimush** [comment]
I can also confirm that it works on macos. It's a bit annoying though to remember to run `darwin-rebuild` on reboot. I guess a launchd service would be needed to overcome this.

**Comment by alexghr** [comment]
Hey, to add to this, I have migrated my nix config to this fork of agenix and I can confirm that it works with both NixOS and nix-darwin. I've got the same config shared by two different systems :raised_hands:

**Comment by rtimush** [comment]
As a follow-up to my previous comment, [this](https://github.com/montchr/agenix/compare/darwin-support...rtimush:agenix:darwin-support) is the branch that adds a launchd script activating secrets on boot. I haven't tested it too thoroughly, but it works for me.

**Comment by misuzu** [comment]
Any updates on this?

**Comment by ryantm** [comment]
This is looking simpler than I remembered! My main concern (beyond needing another round of merge conflict fixes) is having some kind of test for this in GitHub Actions. I'm worried people working only on NixOS will break it by accident.

**Comment by ryantm** [comment]
Maybe this can provide some inspiration for making a GitHub action for testing this? https://github.com/LnL7/nix-darwin/blob/master/.github/workflows/test.yml

**Comment by montchr** [comment]
Hey all, sorry for the delay in getting back to this. I did not have access to a Mac for a few months, as I only use it when provided as a work computer and I recently changed employers... After many delays, I now have a new `aarch64-darwin` laptop running with my existing nix-darwin/home-manager configs.

So with all that said, I'll fix the merge conflicts and look into adding some tests.

**Comment by montchr** [comment]
Well, quite a lot has changed here in the past few months! The conflicts unfortunately don't appear to have a straightforward resolution, as the underlying approaches changed on `main` since this branch was originally cut. So I'm thinking it may be best to start this work over on a new branch from the current state of `main` and compare with my additions on this branch.

**Comment by rtimush** [comment]
Speaking of the GitHub Action tests, I have actually added some to my branch (https://github.com/rtimush/agenix/commit/bc6d15167e8d0007341a92843ee12f33c7842c9b) before I realized that there are so many conflicts to resolve.

**Comment by JayRovacsek** [comment]
Keen to help if it's needed at all @montchr, super keen to have `age` behaving nicely under one flake input :grin:

**Comment by n8henrie** [comment]
@ryantm @montchr @rtimush 

It looks like this has stalled a bit -- I'm a relatively new nix user and brand new to agenix, looking for a solution for secrets on aarch64-darwin (nix-darwin, my primary machine), aarch64-linux (nixos), and nixos x86_64-linux (nixos), and it looks like agenix is probably the best solution.

Because the merge conflicts were a little too hairy for me to rebase, I tried to manually pluck them out as well as add in the launchd code and the GitHub Actions tests. I've put it together in https://github.com/ryantm/agenix/pull/141 -- I hope you don't mind me piggybacking off your work.

The provided tests are passing but I **don't think it's ready to merge**, as I am still trying to figure out how all this works, and trying to make sure I remapped the dependencies properly for things like `installNonRootSecrets` that no longer exist. I would love if we can get a few extra eyes on this and hopefully get it merged!

**Comment by n8henrie** [comment]
> It's a bit annoying though to remember to run darwin-rebuild on reboot. I guess a launchd service would be needed to overcome this.

@rtimush you might not need the launchd script -- do you have https://daiderd.com/nix-darwin/manual/index.html#opt-services.activate-system.enable enabled (default is `true`)?

**Comment by rtimush** [comment]
@n8henrie I do, it's just that `nix-darwin` only runs a couple of built-in scripts on activation, and any custom scripts we add will not be executed:
https://github.com/LnL7/nix-darwin/blob/3db1d870b04b13411f56ab1a50cd32b001f56433/modules/services/activate-system/default.nix#L39-L40

**Pull request closed without merging**
