### PR TITLE
feature: pipe cleartext into agenix -e

### LINKED ISSUE #33: pipe (generated) key to agenix
I just got agenix set up today. Yay!

I'd like to be able to generate machine keys without a lot of manual steps. It's a small, useful thing and I'd be happy to submit and impl if we can settle on a spec.

Rather than integrating a particular password gen how about adding support for taking the cleartext from stdin?

Either overload the existing `-e` mode:

```
cat /dev/urandom | head -c 128 | agenix -e mysecret.age
```

or add a new mode like `-i`

wdyt?

### PR DESCRIPTION
**Pull request by ryantm**
If STDIN is not interactive, change EDITOR to `cp /dev/stdin`.

Also updates tests somewhat.

fixes #33

### CODE REVIEW

**Review by n8henrie — APPROVED** [review]

**Comment by whentze** [comment]
Oh yikes, this breaks *another* hack of mine where I set `EDITOR` to something else to get plaintext secrets *out* 😬

**Comment by ryantm** [comment]
@whentze Can you describe your hack more?

**Comment by whentze** [comment]
Yes. I have a program like this
```sh
#!/bin/sh
cp "$2" "$1"
```
and by setting it as `$EDITOR` I can programmatically get cleartext secrets out of agenix.
I know I can call `age` directly, but it doesn't have the same logic for finding private keys, so it doesn't work in every case.

**Comment by whentze** [comment]
Just to be clear, I'm aware this is an awful hack, and I'm not asking you to keep it supported.
But maybe another way to get the plaintext secrets out would be nice.

**Comment by ryantm** [comment]
This editor program puts the cleartext into a file called cleartext even with these changes.
```
#!/bin/sh
cp "$1" cleartext
```

**Comment by whentze** [comment]
Huh, even when STDIN is not interactive?

**Comment by ryantm** [comment]
Oh, no STDIN was interactive. I misunderstood what you are doing.

**Comment by whentze** [comment]
Sorry for the edits, I had realized my minimal example was too minimal and didn't actually work.

What the hack is really solving for me is the ability to use agenix secrets in a script - locally while working on a repo.

**Comment by whentze** [comment]
Would you be open to the addition of `agenix --decrypt` or something, that does specifically that without requiring a hack?

I can try my hand at an implementation.

**Comment by ryantm** [comment]
Yes, definitely. We're using `EDITOR=cat` hack a bunch in the tests in lieu of this feature too.

**Comment by n8henrie** [comment]
@whentze can you provide a sample codeblock for how one would interact with this, to make sure I understand?

Is this it?

```console
$ agenix [-i /tmp/id_rsa] --decrypt myfile.age
mysecret
```

**Comment by whentze** [comment]
@n8henrie yes, exactly like that :)

See https://github.com/ryantm/agenix/pull/158 for my attempt at it.

**Pull request merged**
