### PR TITLE
contrib: migrate testing into python module

### PR DESCRIPTION
**Pull request by n8henrie**
[This](This) allows using python linters and tools directly and makes it much
easier to create our own convenience methods.

If we can avoid the trap of excess complexity and configurability, I
think this could facilitate addition of much broader integration tests,
especially for the CLI.

### CODE REVIEW

**Comment by n8henrie** [comment]
This may be a bit much, but I refactored the tests into a separate python module. This ends up having much the same effect as https://github.com/ryantm/agenix/pull/139/files, inasmuch as we can lint and typecheck the test code with the usual Python tools, and even install it as a standalone package if desired.

Unfortunately the typechecking isn't automatically performed as I expected; I think the nixosTest typechecking perhaps happens earlier in the process than I expected; I tried numerous workaround including addition of `py.typed`, `agenix_testing.pyi`, automating `stubgen`, and moving everything to a submodule; the best I got was a submodule that would import without an error, but then a smoketest showed that type checking wasn't being enforced. It ended up being much simpler to just import the module and `type: ignore`; the type hints still work in your editor and so are still helpful.

I think the disadvantages are minor, especially since all the usual methods are still exposed (one can still use `systemd1.shell_whatever` just like before).

I think the advantages are such that it will encourage better / more comprehensive integration testing of the CLI.

The tests currently **fail** because [some of the output](https://github.com/ryantm/agenix/blob/5f66c8aa774d8d488cba1cdc4f0c954d2a14e3a1/pkgs/agenix.sh#L138) that perhaps (?) should go to stderr is instead going to stdout; the old tests used `assert "secret1234" in`... whereas I'm using `==`, which I think is much more precise if we're hoping for consistent noninteractive usage.

**Comment by n8henrie** [comment]
Also, I used `buildPythonPackage` instead of just `sys.path.append("${./.}"); import agenix_testing` in part to make it easier to manage additional python dependencies, should we eventually want them, and it part because it seems like the blessed path.

**Comment by ryantm** [comment]
Did you see my tests in https://github.com/ryantm/agenix/pull/163 where I show we can move the agenix tests to the build of agenix rather than a NixOS test? I wonder if that changes your balance of whether this is worth it to do.

**Comment by n8henrie** [comment]
Busy week! I saw the review request but haven't had much time. Will add a few comments!

**Comment by n8henrie** [comment]
On second thought, I think this is generally "too much" for the goals of this project. I think a larger more robust framework makes more sense for the tool itself, but agenix is mostly a *wrapper* for the tool. I don't expect a lot of de novo feature development to happen here, we just need to make sure that the user-facing behavior is safe and friendly.

So I think I'm

**Pull request closed without merging**
