### PR TITLE
contrib: use jq instead of sed

### PR DESCRIPTION
**Pull request by n8henrie**
Fixes https://github.com/ryantm/agenix/issues/147

### CODE REVIEW

**Comment by n8henrie** [comment]
@ryantm if this doesn't quite fit feel free to close, no hard feelings.

**Comment by n8henrie** [comment]
Actually let me make sure rekeying works. Should probably also add a test for rekeying to CI.

**Comment by ryantm** [comment]
Great if you can add a test. Since this is just the CLI I care a lot less about the closure size!

**Comment by n8henrie** [comment]
I have a WIP PR to expand the current integration test to also include some CLI features (starting with `--rekey`). Learning about NixOS tests as I go -- really cool stuff.

Will rebase this on that -- assuming it's deemed appropriate to merge -- which will help ensure the CLI (and hence this PR) are working as intended.

**Comment by ryantm** [comment]
I just rebased this on master so it would run the rekeying test.

**Review by ryantm — APPROVED** [review]

**Pull request merged**
