### PR TITLE
fix: pin down all binaries outside of coreutils

### PR DESCRIPTION
**Pull request by ryantm**
The default sed was having trouble with newline splitting on MacOS.

supersedes #36

### CODE REVIEW

**Review by asymmetric — APPROVED** [review]
Haven't tested, but looks sane.

**Comment by happysalada** [comment]
Just tested, all good!
Thanks for fixing this fast!

**Review by happysalada — APPROVED** [review]
LGTM

**Comment by happysalada** [comment]
Ah, I missed one sed, and I was testing against the wrong version!
The sed on this line has been missed
https://github.com/ryantm/agenix/pull/37/files#diff-2599b31abea1c3ff13382fbfe215a705aa6c5097528ea2b1517702bcdfc23f5bR168
So sorry to ask you this, but do you think you could replace that sed as well?
If you want me to make a PR, let me know.

**Comment by ryantm** [comment]
@happysalada Fixed in the latest master.

**Comment by happysalada** [comment]
Thanks a lot! ❤️

**Pull request merged**
