### PR TITLE
feature: age-plugin-yubikey support

### PR DESCRIPTION
**Pull request by nrdxp**
This works! ~~, but is in draft mode because of str4d/age-plugin-yubikey#34, which makes usage impractical.~~
[rendered instructions](https://github.com/ryantm/agenix/blob/d702501a84f676b8096fbfbefef1e5df96a86640/README.md#yubikey-support)

### CODE REVIEW

**Comment by ryantm** [comment]
Cool. It would be nice to have some instructions.

**Comment by nrdxp** [comment]
Simple instructions are now included: [rendered](https://github.com/nrdxp/agenix/tree/yubikey#yubikey-support).

Also be sure to read documentation for [age-plugin-yubikey](https://github.com/str4d/age-plugin-yubikey#yubikey-plugin-for-age-clients).

**Comment by nrdxp** [comment]
I don't see any specific doc on yubikey versions, but I would assume that as long as your yubikey has the PIV application available that it should work.

**Comment by ryantm** [comment]
My Yubikey is way too old. It doesn't even have things called "application"s.

**Comment by nrdxp** [comment]
PIN policy has been updated to work with 'never' as expected. Ideally, we would want the 'once' policy to still PIN protect the secrets, but because there is still no agent support for yubikey yet, this would ask for PIN every time.

**Comment by pinpox** [comment]
Any updates on this? Being able to use my yubi would be great as I use it for all my ssh-keys anyway.

**Comment by pinpox** [comment]
This guy seems to be using agenix with yubikeys: https://github.com/johnae/world/blob/8cd4af5a2fc572dd7a49399cf53d862aa841d481/flake.nix#L20

Has anything happen on this topic since 2021? Still interested in this feature
:slightly_smiling_face:

**Comment by pinpox** [comment]
ping @nrdxp Are you still working on this?

**Comment by nrdxp** [comment]
> ping @nrdxp Are you still working on this?

Nope sorry, lost track of this one as I am no longer using agenix personally. I'll close for now, but feel free to steal anything that might be useful for another PR

**Pull request closed without merging**
